name: Check dist/

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'
  workflow_dispatch:

jobs:
  call-check-dist:
    if: github.event.pull_request.user.login != 'dependabot[bot]'
    name: Check dist/
    uses: actions/reusable-workflows/.github/workflows/check-dist.yml@main
